name: bibti
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.0.0
  google_maps_flutter: ^2.0.9
  flutter_speed_dial: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Kollektif
      fonts:
       - asset: fonts/Kollektif.ttf
       - asset: fonts/Kollektif-Bold.ttf
         weight: 700
       - asset: fonts/Kollektif-BoldItalic.ttf
       - asset: fonts/Kollektif-Italic.ttf
         style: italic

    - family: Gilroy Light
      fonts:
       - asset: fonts/gilroy-light.otf

    - family: Coves
      fonts:
        - asset: fonts/Coves-Bold.otf
        - asset: fonts/Coves-Light.otf

